### ISSUE TITLE
Zod 3.20 and TS 4.5+ Causes tsserver High CPU

### ISSUE THREAD

**Issue by arnm** [colinhacks/zod#2142]
The combination of Zod 3.20 and TS 4.5+ is causing my project tsserver to have considerable slow down and degrades the developer experience.

Other seem to be having the same issues: https://stackoverflow.com/questions/74881472/slow-typescript-autocompletion-in-vs-code-for-zod

**Comment by colinhacks** [comment]
Should be fixed in Zod 3.21

**Comment by arnm** [comment]
Hey @colinhacks Thanks for the quick turn around on this. I am definitely noticing better performance. My previous `tsc --extendedDiagnostics` checks where around 200 seconds for my project. Now it seems to be 95 seconds so huge improvement but obviously still not ideal.

I suspect the remaining 90 seconds are potentially due to my project which uses prisma, zod, trpc combination for 12  prisma models. Its a hefty amount of generated code I guess?

```
Files:                         3094
Lines of Library:             28794
Lines of Definitions:       1276709
Lines of TypeScript:          21722
Lines of JavaScript:            183
Lines of JSON:                    0
Lines of Other:                   0
Identifiers:                1190030
Symbols:                    1588640
Types:                       550143
Instantiations:            12018456
Memory used:               1853568K
Assignability cache size:    152667
Identity cache size:           2151
Subtype cache size:              86
Strict subtype cache size:      103
I/O Read time:                0.28s
Parse time:                   4.58s
ResolveTypeReference time:    0.01s
ResolveModule time:           0.34s
Program time:                 5.73s
Bind time:                    1.56s
Check time:                  86.95s
I/O Write time:               0.00s
printTime time:               0.05s
Emit time:                    0.05s
Total time:                  94.29s
```
