### ISSUE TITLE
Cannot get error message from safeParse

### ISSUE THREAD

**Issue by Creative-Difficulty** [colinhacks/zod#2883]
This should work:
```ts
//or process.env
const parsedEnv = envSchema.safeParse(Bun.env);
//@ts-ignore
if(parsedEnv.success === false) { console.error(parsedEnv.error.message); process.exit(1); }

```
but it doesn't.
Instead i have to do these shenanigans:
```ts
const parsedEnv = envSchema.safeParse(Bun.env);
if(parsedEnv.success === false) { console.error(JSON.parse(parsedEnv.error.message)[0].message); process.exit(1); }

```

**Comment by Creative-Difficulty** [comment]
@colinhacks pls fix

**Comment by amany9000** [comment]
@colinhacks @Creative-Difficulty, I'm facing the same issue

**Comment by Creative-Difficulty** [comment]
@amany9000 There's a quite easy workaround

**Comment by blackram** [comment]
```
import { z } from 'zod'

const check = (env) => {
    const parsedEnv = z.string().safeParse(env);

    if(parsedEnv.success === false) { 
        console.error(parsedEnv.error.message); 
        process.exit(1); 
    } else {
        console.log('success!')
    }
}
check('1')
check(1)
```

when run 

```% node zod-repro.mjs```
```
success!
[
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "number",
    "path": [],
    "message": "Expected string, received number"
  }
]
```

with: zod@^3.22.4

**Comment by Creative-Difficulty** [comment]
No it isn't

**Comment by cloudbring** [comment]
I'm seeing the same issue. Here's my code where I'm seeing it.

```ts
const envSchema = z.object({
  NODE_ENV: z.string().default("development"),

  // FOO
  FOO_API_KEY: z.string(),

  // BAR
  BAR_KEY: z.string(),
  BAR_REGION: z.string(),
})

const parsed = envSchema.safeParse(process.env)

if (!parsed.success) {
  console.error(
    `Error #%d: Failed Parsing .env file.
    Please ensure that it exists and is valid: `,
    JSON.stringify(parsed.error.format(), null, 4)
    //                    ^^^^^
  );
  process.exit(1);
} else {
 ...
}
```

VSCode Error for the underlined object:

> Property 'error' does not exist on type 'SafeParseReturnType<{ NODE_ENV?: string; FOO_API_KEY?: string; BAR_KEY?: string; BAR_REGION?: string; }, { NODE_ENV?: string; FOO_API_KEY?: string; BAR_KEY?: string; BAR_REGION?: string; }>'.
>   Property 'error' does not exist on type 'SafeParseSuccess<{ NODE_ENV?: string; FOO_API_KEY?: string; BAR_KEY?: string; BAR_REGION?: string; }>'.ts(2339)

**Comment by jeremydaly** [comment]
Do you have `strict: true` set in your `tsconfig.json`? I was getting this error when I had it set to `false`.

**Comment by Creative-Difficulty** [comment]
This has nothing to do with strict mode.

**Comment by impuLssse** [comment]
I have same problem, 
<img width="891" alt="image" src="https://github.com/colinhacks/zod/assets/86838048/c1cc2c3e-eb1e-4aac-b852-5958937dcffc">
<img width="1480" alt="image" src="https://github.com/colinhacks/zod/assets/86838048/7b73966c-b872-4f51-8560-b444168a4802">

**Comment by Creative-Difficulty** [comment]
This is still an issue

**Comment by nbolton** [comment]
Same here.
![image](https://github.com/colinhacks/zod/assets/313427/8f436582-5b61-4960-924d-c60b82403d1b)

**Comment by MarcosNicolau** [comment]
I solved this with a custom wrapper using parse instead of safeParse

```typescript
import { z } from "zod";

type ZodParse = <T extends z.ZodType>(
	schema: T,
	objToparse: z.infer<T>
) => Promise<{ err: z.ZodError | null; output: z.infer<T> | null; success: boolean }>;

export const zodParseAsync: ZodParse = async (schema, objToParse) => {
	try {
		const output = await schema.parseAsync(objToParse);
		return { success: true, output: output, err: null };
	} catch (error: any) {
		const err: z.ZodError = error;
		return { success: false, output: null, err };
	}
};
```

**Comment by GrahamS-Quartech** [comment]
This is still an issue in 2024. Considering the above works, it seems that it's just the type definitions that are broken.

**Comment by Eiley2** [comment]
Same, currenty facing this issue

**Comment by Shisuki** [comment]
This is not longer an issue if you don't use deconstruction

In here `parsingResult.error` is defined but weirdly it's not defined when you try to deconstruct it.

<img width="682" alt="image" src="https://github.com/colinhacks/zod/assets/12876340/e67072ff-0d52-4ece-a66a-34b8d741f4fe">

**Comment by sir-captainmorgan21** [comment]
@Shisuki I just installed the latest version for the first time and came here looking for an answer, but Im stil seeing what people above were seeing. Anymore information you can provide?

**Comment by sir-captainmorgan21** [comment]
It works if you do `result.success === false`. But !result.success` doesn't work...

**Comment by vjlkof** [comment]
Thanks for the solution my friend

**Comment by colinhacks** [comment]
You need to enable `strictNullChecks: true` or `strict: true`. Once enabled you will not see this error. This is a requirement for Zod to properly type the results of parsing.

**Comment by Pinky030** [comment]
I am still encountering this error. I have set `strict: true`  in my `tsconfig.json`.

Tried `result.success === false` as a workaround solution but the build is still failing and returns an error message from safeParse

**Comment by Pinky030** [comment]
> I am still encountering this error. I have set `strict: true` in my `tsconfig.json`.
> 
> Tried `result.success === false` as a workaround solution but the build is still failing and returns an error message from safeParse

It works when:

```
    if(result.success) { 
        const {data} = result;
        return data
    } 
```

**Comment by Downster** [comment]
So I believe this issue is still present and may have been misunderstood. I am not having any issues with the types, however the return type for `parsed.error.message` is wrong. It says I should receive a string, but I actually receive an array with one error object inside of it, like so:
```ts
[
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "number",
    "path": [],
    "message": "Expected string, received number"
  }
]
```

So, if you follow the documentation and provide `parsed.error.message` to the frontend, the frontend will show a JSON object. My current workaround is a function that grabs the error message like so:

```ts
export function getZodErrorMessage(error: z.ZodError): string {
  const message = error.message;
  const parsedMessage = JSON.parse(message) as Array<{ message: string }>;
  const zodError = parsedMessage[0];
  if (!zodError) throw Error("Zod is broken");
  return zodError.message;
}
```

However, I don't think this should be necessary. It would be nice if this was fixed at some point in the future! Thanks 😄

**Comment by aaronhipple** [comment]
> So I believe this issue is still present and may have been misunderstood. I am not having any issues with the types, however the return type for `parsed.error.message` is wrong. [...]

Per today's code I think the type is actually technically correct (the best kind of correct):

https://github.com/colinhacks/zod/blob/f7ad26147ba291cb3fb257545972a8e00e767470/src/ZodError.ts#L286-L288

i.e. the output of the `message` getter is indeed a string, but a string of JSON rather than a human-readable message (as one might expect given the field's name).

I've opened #3937 to start a discussion about possible resolutions (starting with just a comment clarifying what the field actually returns).

**Comment by colinhacks** [comment]
`ZodError` extends `Error` and the `message` property is always a string: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message

The `message` of a ZodError is a JSON.stringified issues array as has been noted elsewhere. The types are not wrong, this is very much intentional to make the `message` property as informative as possible for logging, etc. You should use `.issues` to retrieve granular error information rather than `JSON.parse(err.message)`. Everything here is intentional and expected.

Other people on here are describing an unrelated issue: `Property error is not defined`. This was fixed in https://github.com/colinhacks/zod/pull/3295 and released in Zod 3.23 last April.

**Comment by aaronhipple** [comment]
> `ZodError` extends `Error` and the `message` property is always a string: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message
> 
> The `message` of a ZodError is a JSON.stringified issues array as has been noted elsewhere. The types are not wrong, and this is an intentional decision to make the `message` property as informative as possible for logging, etc. You should use `.issues` to retrieve granular error information rather than `JSON.parse(err.message)`. Everything here is intentional and expected.

Makes a lot of sense and is good information -- it'd be extra-useful if it was straightforward to find in documentation or inline in the code (per #3937, which I have updated to include this explanation specifically).

**Comment by SupertigerDev** [comment]
still not fixed, why is this closed, maybe it only happens on bun idk

**Comment by nairvijays99** [comment]
> still not fixed, why is this closed, maybe it only happens on bun idk

Instead of accessing `errors` property, use `issues`. 

Ex:
```
const parseResult = inputSchema.safeParse(body);

if (!parseResult.success) {
  const errors = parseResult.error.issues;
  console.log(errors)
}
```
